//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int deviceID { get; set; }
        public string deviceName { get; set; }
        public string deviceIp { get; set; }
        public string wifiName { get; set; }
        public string wifiPassword { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string mailAddress { get; set; }
        public string mailPassword { get; set; }
        public string status { get; set; }
        public string waterLevel { get; set; }
        public string frequency { get; set; }
    }
}
